[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remapping = ["@chainlink/=lib/chainlink-brownie-contracts/"]
remappings = ["@=lib"]
fs_permissions = [
    { access = "read", path = "./broadcast"},
    { access = "read", path = "./reports"}
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
